import { index, integer, primaryKey, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
const timestamps = { createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()), updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()) };
export const allusions = sqliteTable("allusions", { id:text("id").primaryKey(), title:text("title").notNull(), slug:text("slug").notNull(), pinyin:text("pinyin").notNull().default(""), summary:text("summary").notNull().default(""), meaning:text("meaning").notNull().default(""), story:text("story").notNull().default(""), usageNotes:text("usage_notes").notNull().default(""), searchText:text("search_text").notNull().default(""), status:text("status",{enum:["draft","review","published","archived"]}).notNull().default("draft"), qualityLevel:integer("quality_level").notNull().default(0), ...timestamps, publishedAt:integer("published_at",{mode:"timestamp"}) }, t=>[uniqueIndex("allusions_slug_uq").on(t.slug),index("allusions_title_idx").on(t.title),index("allusions_status_idx").on(t.status),index("allusions_quality_idx").on(t.qualityLevel),index("allusions_updated_idx").on(t.updatedAt)]);
export const aliases=sqliteTable("allusion_aliases",{id:text("id").primaryKey(),allusionId:text("allusion_id").notNull().references(()=>allusions.id,{onDelete:"cascade"}),alias:text("alias").notNull(),aliasType:text("alias_type").notNull().default("alternate"),createdAt:timestamps.createdAt},t=>[uniqueIndex("aliases_allusion_alias_uq").on(t.allusionId,t.alias),index("aliases_allusion_idx").on(t.allusionId),index("aliases_alias_idx").on(t.alias)]);
export const works=sqliteTable("works",{id:text("id").primaryKey(),title:text("title").notNull(),slug:text("slug").notNull(),authorText:text("author_text"),dynasty:text("dynasty"),description:text("description"),...timestamps},t=>[uniqueIndex("works_slug_uq").on(t.slug)]);
export const people=sqliteTable("people",{id:text("id").primaryKey(),name:text("name").notNull(),slug:text("slug").notNull(),dynasty:text("dynasty"),birthYear:integer("birth_year"),deathYear:integer("death_year"),summary:text("summary"),...timestamps},t=>[uniqueIndex("people_slug_uq").on(t.slug)]);
export const sources=sqliteTable("allusion_sources",{id:text("id").primaryKey(),allusionId:text("allusion_id").notNull().references(()=>allusions.id,{onDelete:"cascade"}),workId:text("work_id").references(()=>works.id),sourceType:text("source_type",{enum:["primary","secondary","related"]}).notNull(),chapter:text("chapter"),originalText:text("original_text"),translation:text("translation"),note:text("note"),referenceNote:text("reference_note"),sortOrder:integer("sort_order").notNull().default(0),...timestamps},t=>[index("sources_allusion_idx").on(t.allusionId),index("sources_work_idx").on(t.workId)]);
export const examples=sqliteTable("examples",{id:text("id").primaryKey(),allusionId:text("allusion_id").notNull().references(()=>allusions.id,{onDelete:"cascade"}),quote:text("quote").notNull(),authorText:text("author_text"),workTitle:text("work_title"),dynasty:text("dynasty"),personId:text("person_id").references(()=>people.id),workId:text("work_id").references(()=>works.id),explanation:text("explanation"),referenceNote:text("reference_note"),sortOrder:integer("sort_order").notNull().default(0),...timestamps},t=>[index("examples_allusion_idx").on(t.allusionId),index("examples_person_idx").on(t.personId),index("examples_work_idx").on(t.workId)]);
function taxonomy(name:string){return sqliteTable(name,{id:text("id").primaryKey(),name:text("name").notNull(),slug:text("slug").notNull(),description:text("description"),parentId:text("parent_id"),sortOrder:integer("sort_order").notNull().default(0),...timestamps},t=>[uniqueIndex(`${name}_slug_uq`).on(t.slug),index(`${name}_parent_idx`).on(t.parentId)]);}
export const scenarios=taxonomy("scenarios"),categories=taxonomy("categories"),tags=taxonomy("tags");
export const allusionScenarios=sqliteTable("allusion_scenarios",{allusionId:text("allusion_id").notNull().references(()=>allusions.id,{onDelete:"cascade"}),scenarioId:text("scenario_id").notNull().references(()=>scenarios.id,{onDelete:"restrict"}),relevance:integer("relevance").notNull().default(50),isPrimary:integer("is_primary",{mode:"boolean"}).notNull().default(false)},t=>[primaryKey({columns:[t.allusionId,t.scenarioId]}),index("as_scenario_idx").on(t.scenarioId)]);
export const allusionCategories=sqliteTable("allusion_categories",{allusionId:text("allusion_id").notNull().references(()=>allusions.id,{onDelete:"cascade"}),categoryId:text("category_id").notNull().references(()=>categories.id,{onDelete:"restrict"})},t=>[primaryKey({columns:[t.allusionId,t.categoryId]}),index("ac_category_idx").on(t.categoryId)]);
export const allusionTags=sqliteTable("allusion_tags",{allusionId:text("allusion_id").notNull().references(()=>allusions.id,{onDelete:"cascade"}),tagId:text("tag_id").notNull().references(()=>tags.id,{onDelete:"restrict"})},t=>[primaryKey({columns:[t.allusionId,t.tagId]}),index("at_tag_idx").on(t.tagId)]);
export const allusionPeople=sqliteTable("allusion_people",{allusionId:text("allusion_id").notNull().references(()=>allusions.id,{onDelete:"cascade"}),personId:text("person_id").notNull().references(()=>people.id,{onDelete:"restrict"}),role:text("role").notNull().default("related"),sortOrder:integer("sort_order").notNull().default(0)},t=>[primaryKey({columns:[t.allusionId,t.personId,t.role]}),index("ap_person_idx").on(t.personId)]);
export const relatedAllusions=sqliteTable("related_allusions",{allusionId:text("allusion_id").notNull().references(()=>allusions.id,{onDelete:"cascade"}),relatedAllusionId:text("related_allusion_id").notNull().references(()=>allusions.id,{onDelete:"cascade"}),relationType:text("relation_type",{enum:["similar","opposite","related","easily_confused"]}).notNull(),score:integer("score").notNull().default(50),note:text("note")},t=>[primaryKey({columns:[t.allusionId,t.relatedAllusionId,t.relationType]}),index("related_target_idx").on(t.relatedAllusionId)]);
export const revisions=sqliteTable("entity_revisions",{id:text("id").primaryKey(),entityType:text("entity_type").notNull(),entityId:text("entity_id").notNull(),snapshotJson:text("snapshot_json").notNull(),changedBy:text("changed_by"),createdAt:timestamps.createdAt},t=>[index("revisions_entity_idx").on(t.entityType,t.entityId)]);
export const aiRuns=sqliteTable("ai_runs",{id:text("id").primaryKey(),taskType:text("task_type").notNull(),entityType:text("entity_type").notNull(),entityId:text("entity_id"),provider:text("provider"),model:text("model"),promptVersion:text("prompt_version"),inputHash:text("input_hash"),inputJson:text("input_json").notNull(),outputJson:text("output_json"),status:text("status").notNull().default("pending"),error:text("error"),createdAt:timestamps.createdAt,completedAt:integer("completed_at",{mode:"timestamp"})});
export const aiSuggestions=sqliteTable("ai_suggestions",{id:text("id").primaryKey(),aiRunId:text("ai_run_id").notNull().references(()=>aiRuns.id),entityType:text("entity_type").notNull(),entityId:text("entity_id").notNull(),fieldName:text("field_name").notNull(),suggestedValue:text("suggested_value").notNull(),confidence:real("confidence"),status:text("status",{enum:["pending","accepted","rejected"]}).notNull().default("pending"),createdAt:timestamps.createdAt,reviewedAt:integer("reviewed_at",{mode:"timestamp"})},t=>[index("suggestions_entity_idx").on(t.entityType,t.entityId)]);
export const importBatches=sqliteTable("import_batches",{id:text("id").primaryKey(),name:text("name").notNull(),source:text("source"),status:text("status").notNull().default("pending"),totalCount:integer("total_count").notNull().default(0),successCount:integer("success_count").notNull().default(0),errorCount:integer("error_count").notNull().default(0),createdAt:timestamps.createdAt,completedAt:integer("completed_at",{mode:"timestamp"})});
export const importItems=sqliteTable("import_items",{id:text("id").primaryKey(),batchId:text("batch_id").notNull().references(()=>importBatches.id),rawJson:text("raw_json").notNull(),matchedAllusionId:text("matched_allusion_id").references(()=>allusions.id),status:text("status").notNull().default("pending"),error:text("error"),createdAt:timestamps.createdAt},t=>[index("import_items_batch_idx").on(t.batchId)]);
// Better Auth tables. Registration remains disabled; administrators are provisioned out of band.
export const user=sqliteTable("user",{id:text("id").primaryKey(),name:text("name").notNull(),email:text("email").notNull(),emailVerified:integer("email_verified",{mode:"boolean"}).notNull().default(false),image:text("image"),createdAt:integer("created_at",{mode:"timestamp"}).notNull(),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull()},t=>[uniqueIndex("user_email_uq").on(t.email)]);
export const session=sqliteTable("session",{id:text("id").primaryKey(),expiresAt:integer("expires_at",{mode:"timestamp"}).notNull(),token:text("token").notNull(),createdAt:integer("created_at",{mode:"timestamp"}).notNull(),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull(),ipAddress:text("ip_address"),userAgent:text("user_agent"),userId:text("user_id").notNull().references(()=>user.id,{onDelete:"cascade"})},t=>[uniqueIndex("session_token_uq").on(t.token),index("session_user_idx").on(t.userId)]);
export const account=sqliteTable("account",{id:text("id").primaryKey(),accountId:text("account_id").notNull(),providerId:text("provider_id").notNull(),userId:text("user_id").notNull().references(()=>user.id,{onDelete:"cascade"}),accessToken:text("access_token"),refreshToken:text("refresh_token"),idToken:text("id_token"),accessTokenExpiresAt:integer("access_token_expires_at",{mode:"timestamp"}),refreshTokenExpiresAt:integer("refresh_token_expires_at",{mode:"timestamp"}),scope:text("scope"),password:text("password"),createdAt:integer("created_at",{mode:"timestamp"}).notNull(),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull()},t=>[index("account_user_idx").on(t.userId)]);
export const verification=sqliteTable("verification",{id:text("id").primaryKey(),identifier:text("identifier").notNull(),value:text("value").notNull(),expiresAt:integer("expires_at",{mode:"timestamp"}).notNull(),createdAt:integer("created_at",{mode:"timestamp"}),updatedAt:integer("updated_at",{mode:"timestamp"})});
