PRAGMA foreign_keys=ON;
INSERT OR IGNORE INTO scenarios VALUES('s1','失败后复出','dong-shan-zai-qi-scenario',NULL,NULL,0,unixepoch(),unixepoch());
INSERT OR IGNORE INTO allusions VALUES('a1','东山再起','dong-shan-zai-qi','dōng shān zài qǐ','比喻失势或退隐后重新恢复地位、取得成功。','重新复出并取得成就。','谢安早年隐居东山，朝廷屡次征召后出仕，最终建立功业。','适合表达经历低谷、退出或失势后重新取得成功。','东山再起 比喻失势或退隐后重新恢复地位、取得成功。 重新复出并取得成就。 适合表达经历低谷、退出或失势后重新取得成功。 失败后复出','published',1,unixepoch(),unixepoch(),unixepoch());
INSERT OR IGNORE INTO allusion_scenarios VALUES('a1','s1',90,1);
INSERT OR IGNORE INTO scenarios VALUES('s2','背水一战','po-fu-chen-zhou-scenario',NULL,NULL,1,unixepoch(),unixepoch());
INSERT OR IGNORE INTO allusions VALUES('a2','破釜沉舟','po-fu-chen-zhou','pò fǔ chén zhōu','比喻下定决心、不留退路地奋战到底。','以断绝退路表示必胜的决心。','项羽渡过漳河后命令砸锅沉船，只带数日粮食，激励将士决战。','用于形容为达成目标而断绝退路、全力以赴。','破釜沉舟 比喻下定决心、不留退路地奋战到底。 以断绝退路表示必胜的决心。 用于形容为达成目标而断绝退路、全力以赴。 背水一战','published',1,unixepoch(),unixepoch(),unixepoch());
INSERT OR IGNORE INTO allusion_scenarios VALUES('a2','s2',90,1);
INSERT OR IGNORE INTO scenarios VALUES('s3','改变志向','tou-bi-cong-rong-scenario',NULL,NULL,2,unixepoch(),unixepoch());
INSERT OR IGNORE INTO allusions VALUES('a3','投笔从戎','tou-bi-cong-rong','tóu bǐ cóng róng','指文人放弃文职，投身军旅、建功边疆。','放下笔墨参加军队。','班超不甘长期替官府抄写文书，投身军旅并出使西域。','用于表达弃文从武或转换道路、追求更大功业。','投笔从戎 指文人放弃文职，投身军旅、建功边疆。 放下笔墨参加军队。 用于表达弃文从武或转换道路、追求更大功业。 改变志向','published',1,unixepoch(),unixepoch(),unixepoch());
INSERT OR IGNORE INTO allusion_scenarios VALUES('a3','s3',90,1);
INSERT OR IGNORE INTO scenarios VALUES('s4','作品风行','luo-yang-zhi-gui-scenario',NULL,NULL,3,unixepoch(),unixepoch());
INSERT OR IGNORE INTO allusions VALUES('a4','洛阳纸贵','luo-yang-zhi-gui','luò yáng zhǐ guì','形容作品广受欢迎，风行一时。','作品流传甚广，受到热烈欢迎。','左思写成《三都赋》后，洛阳人竞相传抄，一时纸价上涨。','适合赞誉文章、著作流传广泛、影响巨大。','洛阳纸贵 形容作品广受欢迎，风行一时。 作品流传甚广，受到热烈欢迎。 适合赞誉文章、著作流传广泛、影响巨大。 作品风行','published',1,unixepoch(),unixepoch(),unixepoch());
INSERT OR IGNORE INTO allusion_scenarios VALUES('a4','s4',90,1);
INSERT OR IGNORE INTO scenarios VALUES('s5','忍辱奋发','wo-xin-chang-dan-scenario',NULL,NULL,4,unixepoch(),unixepoch());
INSERT OR IGNORE INTO allusions VALUES('a5','卧薪尝胆','wo-xin-chang-dan','wò xīn cháng dǎn','形容刻苦自励，发愤图强。','忍受艰苦，提醒自己不忘目标。','越王勾践战败后忍辱负重，以柴薪和苦胆警醒自己，最终复国。','用于表达在挫折后忍耐奋发、长期准备。','卧薪尝胆 形容刻苦自励，发愤图强。 忍受艰苦，提醒自己不忘目标。 用于表达在挫折后忍耐奋发、长期准备。 忍辱奋发','published',1,unixepoch(),unixepoch(),unixepoch());
INSERT OR IGNORE INTO allusion_scenarios VALUES('a5','s5',90,1);
INSERT OR IGNORE INTO scenarios VALUES('s6','批评空谈','zhi-shang-tan-bing-scenario',NULL,NULL,5,unixepoch(),unixepoch());
INSERT OR IGNORE INTO allusions VALUES('a6','纸上谈兵','zhi-shang-tan-bing','zhǐ shàng tán bīng','比喻只会空谈理论，不能解决实际问题。','脱离实际地空谈理论。','赵括熟读兵书却缺少实战经验，长平之战中导致赵军惨败。','常用于批评脱离现实、缺乏实践的议论或方案。','纸上谈兵 比喻只会空谈理论，不能解决实际问题。 脱离实际地空谈理论。 常用于批评脱离现实、缺乏实践的议论或方案。 批评空谈','published',1,unixepoch(),unixepoch(),unixepoch());
INSERT OR IGNORE INTO allusion_scenarios VALUES('a6','s6',90,1);
INSERT OR IGNORE INTO scenarios VALUES('s7','孤立无援','si-mian-chu-ge-scenario',NULL,NULL,6,unixepoch(),unixepoch());
INSERT OR IGNORE INTO allusions VALUES('a7','四面楚歌','si-mian-chu-ge','sì miàn chǔ gē','比喻陷入四面受敌、孤立无援的困境。','四周都是敌对力量，处境孤立。','项羽被围垓下，夜闻汉军四面唱楚歌，以为楚地尽失。','用于形容受到各方压力、缺少援助的艰难处境。','四面楚歌 比喻陷入四面受敌、孤立无援的困境。 四周都是敌对力量，处境孤立。 用于形容受到各方压力、缺少援助的艰难处境。 孤立无援','published',1,unixepoch(),unixepoch(),unixepoch());
INSERT OR IGNORE INTO allusion_scenarios VALUES('a7','s7',90,1);
INSERT OR IGNORE INTO scenarios VALUES('s8','物归原主','wan-bi-gui-zhao-scenario',NULL,NULL,7,unixepoch(),unixepoch());
INSERT OR IGNORE INTO allusions VALUES('a8','完璧归赵','wan-bi-gui-zhao','wán bì guī zhào','比喻把原物完整无损地归还本人。','将物品完整地交还原主。','蔺相如奉和氏璧出使秦国，以勇气和智慧保全宝玉并送回赵国。','用于承诺或说明把借来的珍贵物品完整归还。','完璧归赵 比喻把原物完整无损地归还本人。 将物品完整地交还原主。 用于承诺或说明把借来的珍贵物品完整归还。 物归原主','published',1,unixepoch(),unixepoch(),unixepoch());
INSERT OR IGNORE INTO allusion_scenarios VALUES('a8','s8',90,1);
