import { and, asc, desc, eq, like, or, sql } from "drizzle-orm";import { getDb } from "@/db";import { aliases,allusions,allusionOrigins,allusionScenarios,originSources,origins,scenarios,sources,works } from "@/db/schema";
export async function listPublished(limit=12){return getDb().select().from(allusions).where(eq(allusions.status,"published")).orderBy(desc(allusions.updatedAt)).limit(limit);}
export async function findPublishedBySlug(slug:string){const [row]=await getDb().select().from(allusions).where(and(eq(allusions.slug,slug),eq(allusions.status,"published"))).limit(1);return row;}
export async function searchPublished(q:string){const pattern=`%${q}%`;return getDb().select({allusion:allusions,score:sql<number>`case when ${allusions.title}=${q} then 100 when ${allusions.title} like ${q+'%'} then 90 when ${allusions.title} like ${pattern} then 85 when exists(select 1 from allusion_aliases a where a.allusion_id=${allusions.id} and a.alias=${q}) then 95 when exists(select 1 from allusion_scenarios x join scenarios s on s.id=x.scenario_id where x.allusion_id=${allusions.id} and s.name=${q}) then 80 when ${allusions.searchText} like ${pattern} then 65 else 0 end`}).from(allusions).where(and(eq(allusions.status,"published"),or(like(allusions.searchText,pattern),like(allusions.title,pattern),sql`exists(select 1 from allusion_aliases a where a.allusion_id=${allusions.id} and a.alias like ${pattern})`))).orderBy(desc(sql`score`),desc(allusions.frequencyLevel),asc(allusions.title)).limit(50);}
export async function detailRelations(id:string){const db=getDb();const [sceneRows,sourceRows,originRows]=await Promise.all([db.select({name:scenarios.name}).from(allusionScenarios).innerJoin(scenarios,eq(allusionScenarios.scenarioId,scenarios.id)).where(eq(allusionScenarios.allusionId,id)).orderBy(desc(allusionScenarios.relevance)),db.select({source:sources,work:works}).from(sources).leftJoin(works,eq(sources.workId,works.id)).where(eq(sources.allusionId,id)).orderBy(asc(sources.sortOrder)),db.select({origin:origins,link:allusionOrigins,source:originSources,work:works}).from(allusionOrigins).innerJoin(origins,eq(allusionOrigins.originId,origins.id)).leftJoin(originSources,eq(originSources.originId,origins.id)).leftJoin(works,eq(originSources.workId,works.id)).where(and(eq(allusionOrigins.allusionId,id),eq(origins.status,"published"))).orderBy(desc(allusionOrigins.isPrimary),asc(allusionOrigins.sortOrder),asc(originSources.sortOrder))]);
  // SQLite aliases are awkward through the query builder; use a compact query for siblings.
  const variants=await db.all<{title:string;slug:string;frequencyLevel:number}>(sql`select distinct a.title, a.slug, a.frequency_level as frequencyLevel from allusion_origin_links own join allusion_origin_links sibling on sibling.origin_id=own.origin_id join allusions a on a.id=sibling.allusion_id where own.allusion_id=${id} and sibling.allusion_id<>${id} and a.status='published' order by a.frequency_level desc,a.title`);
  return {scenarios:sceneRows,sources:sourceRows,origins:originRows,variants};}
export async function listAdmin(){return getDb().select().from(allusions).orderBy(desc(allusions.updatedAt));}
